// packages/spa/src/views/comments/CommentsPanel.vue
<template>
    <transition name="sidebarPanel" @after-enter="triggerResize" @after-leave="triggerResize">
        <aside v-if="isActive" class="app-sidebar-panel screen-comments-panel">
            <header class="app-sidebar-section app-sidebar-header">
                <h4 class="title">{{ $t('Screen comments') }}</h4>
                <div class="list-ctrls">
                    <div class="list-ctrl-item"
                        v-tooltip.left="$t('Close panel')"
                        @click.prevent="hide"
                    >
                        <i class="fe fe-x"></i>
                    </div>
                </div>

                <div v-if="totalActiveScreenComments > 0" class="form-group form-group-switch m-t-20 m-b-5">
                    <input type="checkbox" id="show_resolved" v-model="resolvedCommentsToggle">
                    <label for="show_resolved">{{ $t('Show resolved comments ({count})', {count: totalActiveScreenResolvedComments}) }}</label>
                </div>
            </header>

            <div class="app-sidebar-section app-sidebar-content">
                <div v-if="totalActiveScreenComments <= 0" class="placeholder-block">
                    <div class="icon"><i class="fe fe-message-circle"></i></div>
                    <div class="content">{{ $t("The screen doesn't have any comments yet.") }}</div>
                </div>

                <div v-else-if="!showResolvedComments && totalActiveScreenComments > 0 && !hasUnresolvedComments" class="placeholder-block">
                    <div class="icon"><i class="fe fe-message-circle"></i></div>
                    <div class="content">{{ $t('All screen comments have been resolved.') }}</div>
                </div>

                <div v-else class="cards-list">
                    <div
                        v-for="(comment, i) in activeScreenComments"
                        v-if="!comment.isNew && (!comment.isResolved || showResolvedComments)"
                        class="card comment-card"
                        :class="{
                            'active': activeCommentId == comment.id,
                            'card-danger': isCommentUnread(comment.id)
                        }"
                        @click.prevent="setActiveCommentId(comment.id)"
                    >
                        <figure class="icon">
                            <span class="txt txt-hint">{{ totalActiveScreenComments-i }}</span>
                            <i v-if="comment.isResolved" class="fe fe-check txt-success"></i>
                        </figure>
                        <div class="content">
                            <div class="title txt-default">{{ comment.message }}</div>
                            <div class="meta">
                                <div class="meta-item">{{ comment.user ? comment.user.identifier : comment.from }}</div>
                                <div class="meta-item">{{ comment.createdAtFromNow }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </aside>
    </transition>
</template>

<style lang="scss" scoped>
.screen-comments-panel {
    position: relative;
    left: auto;
    right: auto;
    flex-shrink: 0;
}
</style>

<script>
import { mapState, mapActions, mapGetters } from 'vuex';

export default {
    name: 'comments-panel',
    data() {
        return {
            isActive: false,
        }
    },
    computed: {
        ...mapState({
            activePrototypeId:    state => state.prototypes.activePrototypeId,
            activeScreenId:       state => state.screens.activeScreenId,
            showResolvedComments: state => state.comments.showResolvedComments,
            activeCommentId:      state => state.comments.activeCommentId,
            unreadComments:       state => state.notifications.unreadComments,
        }),
        ...mapGetters({
            getCommentsForScreen: 'comments/getCommentsForScreen',
            isCommentUnread:      'notifications/isCommentUnread',
        }),

        activeScreenComments() {
            return this.getCommentsForScreen(this.activeScreenId).reverse();
        },
        activeScreenResolvedComments() {
            return this.getCommentsForScreen(this.activeScreenId, 'resolved').reverse();
        },
        totalActiveScreenComments() {
            return this.activeScreenComments.length;
        },
        totalActiveScreenResolvedComments() {
            return this.activeScreenResolvedComments.length;
        },
        hasUnresolvedComments() {
            return this.totalActiveScreenResolvedComments < this.totalActiveScreenComments;
        },
        resolvedCommentsToggle: {
            get() {
              return this.showResolvedComments;
            },
            set(value) {
              this.setShowResolvedComments(value);
            },
        },
    },
    methods: {
        ...mapActions({
            setShowResolvedComments: 'comments/setShowResolvedComments',
            setActiveCommentId:      'comments/setActiveCommentId',
        }),

        hide() {
            this.isActive = false;
        },
        show() {
            this.isActive = true;
        },
        toggle() {
            if (this.isActive) {
                this.hide();
            } else {
                this.show();
            }
        },
        // trigger resize event for popovers, tooltips, etc.
        triggerResize() {
            window.dispatchEvent(new Event('resize'));
        },
    },
}
</script>

// ui/src/components/comments/CommentsPanel.svelte
<script>
    import { slide } from "svelte/transition";
    import utils from "@/utils";
    import tooltip from "@/actions/tooltip";
    import { activeScreenPrimaryComments, selectedComment, showResolved } from "@/stores/comments";
    import Field from "@/components/base/Field.svelte";

    export let active = false;

    $: primaryComments = $activeScreenPrimaryComments?.filter((c) => !!c.id);

    $: totalResolved = primaryComments.filter((c) => c.resolved).length;

    $: filteredComments = $showResolved ? primaryComments : primaryComments.filter((c) => !c.resolved);

    $: if (totalResolved == 0) {
        $showResolved = false;
    }

    export function toggle() {
        if (active) {
            hide();
        } else {
            show();
        }
    }

    export function show() {
        active = true;
    }

    export function hide() {
        active = false;
    }
</script>

{#if active}
    <aside
        class="screen-preview-sidebar comments-sidebar"
        transition:slide={{ duration: 200, axis: "x" }}
        on:introend={utils.triggerResize}
        on:outroend={utils.triggerResize}
    >
        <header class="sidebar-section sidebar-header">
            <h6>Screen comments</h6>
            <button
                type="button"
                class="btn btn-sm btn-transparent btn-hint btn-circle close-btn"
                use:tooltip={{ position: "left", text: "Close" }}
                on:click|preventDefault={hide}
            >
                <i class="iconoir-xmark" />
            </button>

            {#if primaryComments.length}
                <Field class="form-field form-field-toggle m-t-xs m-b-5 entrance-top" let:uniqueId>
                    <input
                        type="checkbox"
                        id={uniqueId}
                        disabled={totalResolved == 0}
                        bind:checked={$showResolved}
                    />
                    <label for={uniqueId}>Show resolved comments ({totalResolved})</label>
                </Field>
            {/if}
        </header>
        <div class="sidebar-section sidebar-content">
            {#if !filteredComments.length}
                <div class="placeholder-block entrance-top">
                    <div class="icon">
                        <i class="iconoir-message-alert" />
                    </div>
                    <div class="title txt-disabled">
                        {#if !$showResolved && totalResolved > 0}
                            All comments have been resolved.
                        {:else}
                            No comments found.
                        {/if}
                    </div>
                </div>
            {:else}
                <div class="flex-list primary-comments-list entrance-top">
                    {#each primaryComments as comment, i (comment.id)}
                        {#if $showResolved || !comment.resolved}
                            {@const totalReplies =
                                primaryComments.filter((c) => c.replyTo == comment.id).length || 0}
                            <button
                                type="button"
                                class="bubble primary-comment"
                                class:active={comment.id == $selectedComment?.id}
                                on:click|preventDefault={() => {
                                    $selectedComment = comment;
                                }}
                            >
                                <div class="meta">
                                    <strong class="meta-item number">#{i + 1}</strong>
                                    <span class="meta-item txt-ellipsis">
                                        {utils.getCommentAuthor(comment)}
                                    </span>
                                    {#if comment.resolved}
                                        <span class="meta-item resolved m-l-auto" use:tooltip={"Resolved"}>
                                            <i class="iconoir-double-check txt-success" />
                                        </span>
                                    {/if}
                                </div>
                                <div class="content">
                                    {comment.message}
                                </div>
                                <div class="meta">
                                    <span class="meta-item date">
                                        {utils.relativeDate(comment.created)}
                                    </span>
                                    {#if totalReplies > 0}
                                        <span class="meta-item m-l-auto">
                                            {totalReplies}
                                            {totalReplies == 1 ? "reply" : "replies"}
                                        </span>
                                    {/if}
                                </div>
                            </button>
                        {/if}
                    {/each}
                </div>
            {/if}
        </div>
    </aside>
{/if}
